org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=384m -XX:+UseParallelGC -Dcom.android.tools.r8.threads=2
org.gradle.parallel=false
org.gradle.workers.max=3
systemProp.com.android.tools.r8.threads=2
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.vfs.watch=true
org.gradle.java.home=/home/rayhan/.jdks/jdk-21
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
android.builder.sdkDownload=false
kotlin.daemon.jvm.options=-Xmx512m -XX:MaxMetaspaceSize=256m

